spring.application.name=bookmarkservice

server.port=8003

spring.datasource.url=jdbc:postgresql://localhost:5432/authenticationdb
spring.datasource.username=postgres
spring.datasource.password=Checkmate1@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true